#!/opt/blc/python-2.6.5/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'ZODB==4.0.0','console_scripts','repozo'
__requires__ = 'ZODB==4.0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('ZODB==4.0.0', 'console_scripts', 'repozo')()
    )
